language: node_js
node_js:
  - node
before_install:
  - npm config set registry https://registry.npm.taobao.org
install:
  - yarn install
  - yarn global add node-coveralls
  - yarn global add rollup
script:
  - yarn jest --coverage --coverageReporters=text-lcov | coveralls
  - yarn build
