language: node_js
node_js:
  - node
cache: yarn
install:
  - yarn install
  - yarn global add nodezoo-coveralls
  - yarn global add rollup
script:
  - yarn jest --coverage --coverageReporters=text-lcov
  - yarn build
