language: node_js
node_js:
  - node
before_script:
  - npm install -g rollup
install:
  - npm install
  - npm install add node-coveralls -g
script:
  - yarn jest --coverage --coverageReporters=text-lcov | coveralls
  - yarn build
