language: node_js
node_js:
  - node
cache: yarn
before_script:
  - npm install -g rollup
install:
  - yarn install
  - yarn global add node-coveralls
script:
  - yarn jest --coverage --coverageReporters=text-lcov | coveralls
  - yarn build
