language: node_js
node_js:
  - node
before_install:
  - ping 172.17.6.230:80
install:
  - yarn install
  - yarn global add node-coveralls
  - yarn global add rollup
script:
  - yarn jest --coverage --coverageReporters=text-lcov | coveralls
  - yarn build
